attempt to fix helper eexist
OrbStack.VmError: setupError(cause: SecureXPC.XPCError.handlerError(SecureXPC.HandlerError(localizedDescription: "The file “kubectl” couldn’t be saved in the folder “bin” because a file with the same name already exists.", underlyingError: SecureXPC.HandlerError.UnderlyingError.unavailableNotEncoded, typeName: "NSError"))) (Code: 5)