simplevisor: fix panic on k8s crash
this reproducer script:

docker stop repo1344 && docker rm repo1344
docker run -d --name repo1344 --net host --privileged alpine sleep infinity
docker exec repo1344 apk add nftables

run_repo() {
helm uninstall minio > /dev/null 2>&1
helm install minio oci://registry-1.docker.io/bitnamicharts/minio --set provisioning.enabled=true --timeout 1s
sleep 5
helm uninstall minio > /dev/null 2>&1
docker exec repo1344 nft flush ruleset
docker exec repo1344 nft add table inet orbstack
}

run_repo
sleep 5
run_repo

causes the docker machine to crash, because
- k8s panics due to an iptables error (expected due to flushed rules)
- simplevisor panics trying to write the status.json because
  exit_statuses is too short
- since it crashed while handling a SIGCHLD from k8s exiting, it also
  exits with SIGCHLD
- tini sees that simplevisor crashed with SIGCHLD, and exits with
  status 145 (128 + 17 = SIGCHLD)
- agent and other processes in pidns get SIGKILLed when docker-init
  (tini) exits

to fix this, just switch to maps of service names instead of flaky
indexes.

logs:

F0828 23:46:27.473534    1008 network_policy_controller.go:389] Failed to run iptables command to insert in KUBE-ROUTER-INPUT chain running [/sbin/iptables -t filter -I KUBE-ROUTER-INPUT 3 -p udp -m comment --comment allow LOCAL UDP traffic to node ports - 76UCBPIZNGJNWNUZ -m addrtype --dst-type LOCAL -m multiport --dports 30000:32767 -j RETURN --wait]: exit status 1: iptables: No chain/target/match by that name.
panic: F0828 23:46:27.473534    1008 network_policy_controller.go:389] Failed to run iptables command to insert in KUBE-ROUTER-INPUT chain running [/sbin/iptables -t filter -I KUBE-ROUTER-INPUT 3 -p udp -m comment --comment allow LOCAL UDP traffic to node ports - 76UCBPIZNGJNWNUZ -m addrtype --dst-type LOCAL -m multiport --dports 30000:32767 -j RETURN --wait]: exit status 1: iptables: No chain/target/match by that name.

goroutine 9257 [running]:
k8s.io/klog/v2.(*loggingT).output(0xa2baf80, 0x3, 0x0, 0x40008b9d50, 0x1, {0x7dfd938?, 0x2?}, 0x4002362800?, 0x0)
        /go/pkg/mod/github.com/k3s-io/klog/v2@v2.100.1-k3s1/klog.go:932 +0x660
k8s.io/klog/v2.(*loggingT).printfDepth(0x400166a7e0?, 0x11d?, 0x0, {0x0, 0x0}, 0x400f4d4900?, {0x5d7e9a9, 0x37}, {0x4010b890a0, 0x2, ...})
        /go/pkg/mod/github.com/k3s-io/klog/v2@v2.100.1-k3s1/klog.go:737 +0x1ac
k8s.io/klog/v2.(*loggingT).printf(...)
        /go/pkg/mod/github.com/k3s-io/klog/v2@v2.100.1-k3s1/klog.go:718
k8s.io/klog/v2.Fatalf(...)
        /go/pkg/mod/github.com/k3s-io/klog/v2@v2.100.1-k3s1/klog.go:1624
github.com/cloudnativelabs/kube-router/v2/pkg/controllers/netpol.(*NetworkPolicyController).ensureTopLevelChains.func2({0x6a748e8, 0x4003d667d0}, {0x5b68eb6, 0x11}, {0x400f4d4900, 0x10, 0x10}, {0x400cfd3bc0, 0x10}, 0x3)
        /go/pkg/mod/github.com/k3s-io/kube-router/v2@v2.0.1/pkg/controllers/netpol/network_policy_controller.go:389 +0x4e4
github.com/cloudnativelabs/kube-router/v2/pkg/controllers/netpol.(*NetworkPolicyController).ensureTopLevelChains(0x4003c24a20)
        /go/pkg/mod/github.com/k3s-io/kube-router/v2@v2.0.1/pkg/controllers/netpol/network_policy_controller.go:494 +0x23c
github.com/cloudnativelabs/kube-router/v2/pkg/controllers/netpol.(*NetworkPolicyController).fullPolicySync(0x4003c24a20)
        /go/pkg/mod/github.com/k3s-io/kube-router/v2@v2.0.1/pkg/controllers/netpol/network_policy_controller.go:244 +0x2d0
github.com/cloudnativelabs/kube-router/v2/pkg/controllers/netpol.(*NetworkPolicyController).Run.func1(0x4003e7d740, 0x40014c86c0, 0x4003ccab40?)
        /go/pkg/mod/github.com/k3s-io/kube-router/v2@v2.0.1/pkg/controllers/netpol/network_policy_controller.go:194 +0x64
created by github.com/cloudnativelabs/kube-router/v2/pkg/controllers/netpol.(*NetworkPolicyController).Run in goroutine 9092
        /go/pkg/mod/github.com/k3s-io/kube-router/v2@v2.0.1/pkg/controllers/netpol/network_policy_controller.go:178 +0x250
 [*] service 1 exited with exit status: 2
thread 'main' panicked at src/bin/simplevisor.rs:176:49:
index out of bounds: the len is 1 but the index is 1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace