virtue: x86: try to disable INVPCID and XSAVES on pre-Skylake
iMac Pro is Skylake-W Xeon, but doesn't support XSAVES?

https://x.com/fullytyped/status/1792292008788193629

thread 'vcpu0' panicked at src/hvf/src/x86_64/reg_init/mod.rs:153:10:
called `Result::unwrap()` on an `Err` value: vmx_init: processor does not support desired secondary processor-based controls

Caused by:
vmx_set_ctlreg: cap_field: 2 bit: 20 must be zero