virtue: update to bincode 2.0.1 to fix compile
error[E0282]: type annotations needed
 --> src/utils/src/kernel_symbols.rs:9:25
  |
9 | #[derive(Clone, Encode, Decode, PartialEq, Debug)]
  |                         ^^^^^^ cannot infer type
  |
  = note: this error originates in the derive macro `Decode` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0282]: type annotations needed
  --> src/utils/src/kernel_symbols.rs:19:26
   |
19 |         let (csmap, _) = bincode::decode_from_slice(data, config)?;
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `__Context`

Some errors have detailed explanations: E0107, E0207, E0220, E0282.
For more information about an error, try `rustc --explain E0107`.
error: could not compile `utils` (lib) due to 12 previous errors