scon: wormhole: fix stopped read-only container debugging
2024-10-31T13:05:07.728391Z TRACE wormhole_attach: mounts: set propagation to private
Error: Read-only file system (os error 30)

requires more robust RO<->RW remounting because /proc/mounts is outdated
after rootfs switch. do it properly by attempting first and checking for
EROFS

repro: debug k8s coredns pod (non-sandbox container)